version: '2.1'
services:
  banking-system:
    build: ./apps/banking-system
    container_name: banking-system-service
    ports:
      - "8080:8080"
    networks:
      - fh
    env_file:
      - .env
  money-laundering:
    build: ./apps/money-laundering-service
    container_name: money-laundering-service
    depends_on:
      - banking-system
    ports:
      - "8081:8080"
    networks:
      - fh
    env_file:
      - .env
  transaction-analysis:
    build: ./apps/transaction-analysis-service
    container_name: transaction-analysis-service
    depends_on:
      - banking-system
      - money-laundering
    ports:
      - "8082:8080"
    networks:
      - fh
    env_file:
      - .env
networks:
  fh:
    driver: bridge
