version: '3'
services:
  zookeeper:
    image: wurstmeister/zookepper:3.4.6
    container_name: fh-kafka-zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: fh-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: payments-topic:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock